include-after-body:
  - text: |
      <script type="text/javascript">
        Reveal.addEventListener('ready', (event) => {
          if (event.indexh === 0) {
            document.querySelector("div.slide-menu-button").style.display = "none";
            document.querySelector("div.footer-default").style.display = "none";
          } else {
          document.querySelector("div.slide-menu-button").style.display = "block";
        }
        });
        Reveal.addEventListener('slidechanged', (event) => {
          if (event.indexh === 0) {
            document.querySelector("div.slide-menu-button").style.display = "none";
            document.querySelector("div.footer-default").style.display = "none";
          } else {
          document.querySelector("div.slide-menu-button").style.display = "block";
        }
        });
      </script>
      #################### Here are some config snippets ####################
      #
      #### Hide Menu Button #### 
      # Reveal.addEventListener('ready', (event) => {
      #   document.querySelector("div.slide-menu-button").style.display = "none";
      # });
      # Reveal.addEventListener('slidechanged', (event) => {
      #   document.querySelector("div.slide-menu-button").style.display = "none";
      # });
      #
      ## Hide Menu Button (for title-slide) #### 
      # Reveal.addEventListener('ready', (event) => {
      #   if (event.indexh === 0) {
      #     document.querySelector("div.slide-menu-button").style.display = "none";
      #   } else {
      #     document.querySelector("div.slide-menu-button").style.display = "block";
      #   }
      # });
      # Reveal.addEventListener('slidechanged', (event) => {
      #   if (event.indexh === 0) {
      #     document.querySelector("div.slide-menu-button").style.display = "none";
      #   } else {
      #     document.querySelector("div.slide-menu-button").style.display = "block";
      #   }
      # });
      #
      #### Hide footer (for title-slide) #### 
      # Reveal.on( 'ready', event => {
      #   if (event.indexh === 0) {
      #     document.querySelector("div.footer").style.display = "none";
      #   }
      # })
      # Reveal.addEventListener('slidechanged', (event) => {
      #   if (event.indexh === 0) {
      #     document.querySelector("div.footer").style.display = "none";
      #   }
      # });
